[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "^1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/tuvistavie/securerandom"

[[constraint]]
  name = "github.com/wavefronthq/go-metrics-wavefront"
  version = "^1.0.0"

[[override]]
  name = "github.com/wavefronthq/wavefront-sdk-go"
  revision = "f00573cbdf5db675a3850fdfc9f99e54011dad63"
